pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: npm ci
  displayName: install npm dependencies
- bash: npm test
  env:
    LOOK_A_FAILURE: $(look.aFailure)
    FLAKE_IT_GOOD: $(flake.itGood)
  displayName: unit tests
- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: test-results.xml
    testRunTitle: Test Results
  condition: succeededOrFailed()
